#! /bin/sh

### BEGIN INIT INFO
# Provides:          fancontrolhddtemp
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: fancontrol
# Description:       fan speed regulator
### END INIT INFO

. /lib/lsb/init-functions

[ -f /etc/default/rcS ] && . /etc/default/rcS
PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON_FC_HDD=/usr/sbin/fancontrol-hddtemp
DAEMON_FC=/usr/sbin/fancontrol
DESC="fan speed regulator with hddtemp support"
NAME="fancontrolhddtemp"
PIDFILE_FC_HDD=/var/run/fancontrol-hddtemp.pid
PIDFILE_FC=/var/run/fancontrol.pid
CONF_FC=/etc/fancontrol

test -x $DAEMON_FC || exit 0
test -x $DAEMON_FC_HDD || exit 0

case "$1" in
  start)
  	if [ -f $CONF_FC ] ; then
		if $DAEMON_FC --check $CONF_FC 1>/dev/null 2>/dev/null ; then
			log_daemon_msg "Starting $DESC" "$NAME" "$CONF_FC"

			start-stop-daemon --start --quiet --background --pidfile $PIDFILE_FC_HDD --startas $DAEMON_FC_HDD
 			start-stop-daemon --start --quiet --background --pidfile $PIDFILE_FC --startas $DAEMON_FC $CONF_FC
			log_end_msg $?
		else
			log_failure_msg "Not starting fancontrol, broken configuration file; please re-run pwmconfig."
		fi
	else
		if [ "$VERBOSE" != no ]; then
			log_warning_msg "Not starting fancontrol; run pwmconfig first."
		fi
	fi
	;;
  stop)
	log_daemon_msg "Stopping $DESC" "$NAME"
	start-stop-daemon --stop --quiet --pidfile $PIDFILE_FC --oknodo --startas $DAEMON_FC $CONF_FC
	start-stop-daemon --stop --quiet --pidfile $PIDFILE_FC_HDD --oknodo --startas $DAEMON_FC_HDD
	rm -f $PIDFILE_FC
	rm -f $PIDFILE_FC_HDD
	log_end_msg $?
	;;
  restart)
  	$0 stop
	sleep 3
	$0 start
	;;
  force-reload)
	if start-stop-daemon --stop --test --quiet --pidfile $PIDFILE_FC --startas $DAEMON_FC $CONF_FC ; then
		$0 restart
	fi
	if start-stop-daemon --stop --test --quiet --pidfile $PIDFILE_FC_HDD --startas $DAEMON_FC_HDD ; then
		$0 restart
	fi

	;;
  status)
	status_of_proc $DAEMON_FC $NAME $CONF_FC && exit 0 || exit $?
	;;
  *)
	log_success_msg "Usage: /etc/init.d/fancontrol-hddtemp {start|stop|restart|force-reload|status}"
	exit 1
	;;
esac

exit 0
